---
- name: Create/Delete containers
  hosts: servers
  gather_facts: no
  vars:
    action:
      create: "started"
      delete: "absent"
  tasks:
    - name: Actin on container
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        detach: true
        interactive: true
        tty: true
        purge_networks: true
        state: "{{ action[do] }}"
        networks:
          - name: "{{ vpn_name }}"
      with_items: "{{ containers[inventory_hostname] }}"
      when: containers[inventory_hostname] is defined
