---
- name: Set/Delete Junos configuration from crpd
  hosts: crpds
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Building eonfiguration
      template:
        src: vrf.j2
        dest: "{{ inventory_hostname }}.conf"
      when: containers[physer] is defined
    - name: Load configuration
      juniper_junos_config:
        host: "{{ inventory_hostname }}"
        port: "{{ nc_port }}"
        user: "{{ nc_user }}"
        passwd: "{{ nc_psswd }}"
        load: 'set'
        format: 'set'
        file: "{{ inventory_hostname }}.conf"
      when: containers[physer] is defined
      register: result
      failed_when:
        - '"Failure" in result.msg'
        - '"statement not found" not in result.msg'
    - name: WARNING IN CASE VRF WAS NOT FOUND!!!
      debug:
        msg: VRF WAS NOT FOUND!!!
      when: '"statement not found" in result.msg'
    - name: Remove configuration file
      file:
        path: "{{ inventory_hostname }}.conf"
        state: absent
      when: containers[physer] is defined
