---
- name: test
  hosts: servers
  gather_facts: no
  tasks:
    - name: Create a network with options
      docker_network:
        name: "{{ vpn_name }}"
        driver_options:
          com.docker.network.bridge.name: "{{ vpn_name}}"
          com.docker.network.bridge.enable_ip_masquerade: "false"
        ipam_options:
          subnet: "{{ subnets[inventory_hostname] }}"
